transformation:                           
  target: transformation
  outputs:
    transformation:
      type: duckdb
      path: data/duckdb/mobility_analysis.duckdb
      threads: 4
      extensions:
        - httpfs
      settings:
        s3_endpoint: "{{ env_var('MINIO_ENDPOINT', 'localhost:9000') }}"
        s3_access_key_id: "{{ env_var('MINIO_ACCESS_KEY', 'minioadmin') }}"
        s3_secret_access_key: "{{ env_var('MINIO_SECRET_KEY', 'miniopassword') }}"
        s3_use_ssl: false
        s3_url_style: path
