INSERT
    OR REPLACE INTO DIM_STATION
SELECT
    ID,
    CODE,
    NAME,
    ADDRESS,
    LONGITUDE,
    LATITUDE,
    STATUS,
    CAPACITTY
FROM
    CONSOLIDATE_STATION
WHERE
    CREATED_DATE = (
        SELECT
            MAX(CREATED_DATE)
        FROM
            CONSOLIDATE_STATION
    );

INSERT
    OR REPLACE INTO DIM_CITY
SELECT
    ID,
    NAME,
    NB_INHABITANTS
FROM
    CONSOLIDATE_CITY
WHERE
    CREATED_DATE = (
        SELECT
            MAX(CREATED_DATE)
        FROM
            CONSOLIDATE_CITY
    );

INSERT
    OR REPLACE INTO FACT_STATION_STATEMENT
SELECT
    STATION_ID,
    cc.ID as CITY_ID,
    BICYCLE_DOCKS_AVAILABLE,
    BICYCLE_AVAILABLE,
    LAST_STATEMENT_DATE,
    current_date as CREATED_DATE
FROM
    CONSOLIDATE_STATION_STATEMENT
    JOIN CONSOLIDATE_STATION ON CONSOLIDATE_STATION.ID = CONSOLIDATE_STATION_STATEMENT.STATION_ID
    LEFT JOIN CONSOLIDATE_CITY as cc ON cc.ID = CONSOLIDATE_STATION.CITY_CODE
WHERE
    CITY_CODE != 0
    AND CONSOLIDATE_STATION_STATEMENT.CREATED_DATE = (
        SELECT
            MAX(CREATED_DATE)
        FROM
            CONSOLIDATE_STATION_STATEMENT
    )
    AND CONSOLIDATE_STATION.CREATED_DATE = (
        SELECT
            MAX(CREATED_DATE)
        FROM
            CONSOLIDATE_STATION
    )
    AND cc.CREATED_DATE = (
        SELECT
            MAX(CREATED_DATE)
        FROM
            CONSOLIDATE_CITY
    );